# **Kaczmarz Algorithm**

The Kaczmarz algorithm is an iterative method for solving systems of linear equations of the form:

$$
Ax = b
$$

Where:
- \(A\) is a matrix of size \(m \times n\),
- \(x\) is the vector of unknowns,
- \(b\) is the vector of results.

### **Mathematical Method**

Given a current estimate \(x_k\), the update for the next iteration \(x_{k+1}\) is calculated by projecting the current solution onto the hyperplane defined by the \(i\)-th row \(a_i\) of matrix \(A\). The update formula is:

$$
x_{k+1} = x_k + \frac{b_i - a_i^T x_k}{\|a_i\|^2} a_i
$$

Where:
- \(a_i\) is the \(i\)-th row of the matrix \(A\),
- \(b_i\) is the corresponding element of vector \(b\),
$$ \|a_i\|^2\ $$ 
-  is the squared norm of \(a_i\),
- \(x_k\) is the current estimate of the solution.

This formula is applied iteratively for each row of \(A\) until convergence.

### **Algorithm Explanation**:

At each iteration \(k\), the current estimate \(x_k\) is projected onto the hyperplane defined by the equation:

$$
a_i^T x = b_i
$$

The projection step is:

$$
x_{k+1} = x_k + \frac{b_i - a_i^T x_k}{\|a_i\|^2} a_i
$$

This process repeats for each row \(a_i\) of the matrix \(A\), updating the vector \(x\) until the solution converges. The stopping criterion is based on either a tolerance (a small enough difference between \(x_k\) and \(x_{k+1}\)) or a maximum number of iterations.

# **Begin of Algorithm**
need to compute this piece of code to get the value 

this work for all algortym 


In [63]:
import numpy as np

A = np.array([[1325, 5245, 123],
              [5, -44343, -400],
              [1, 408, 4]])

b = np.array([10, -2, 30])

In [38]:
import numpy as np

# Matrix A and vector b
A = np.array([[4, 1, 2],
              [3, 5, 1],
              [1, 1, 3]])

b = np.array([4, 7, 3])

In [53]:
# Random initialization of vector x
x = np.random.rand(3)

In [64]:
# Parameters for the algorithm
tolerance = 1e-6
max_iterations = 10000
alpha = 0.9

### **Python Example**:

In [65]:
# Kaczmarz algorithm
def KacZmarz(A, b, x, tolerance, max_iterations):
    for iteration in range(max_iterations):
        x_old = x.copy()  # Copy old solution
        for i, row in enumerate(A):
            dot_product = np.dot(row, x)  # Compute dot product a_i * x
            norm_squared = np.dot(row, row)  # Compute ||a_i||^2
            x = x + (b[i] - dot_product) / norm_squared * row  # Update x
        # Check for convergence
        if np.linalg.norm(x - x_old) < tolerance:
            print(f"Converged after {iteration + 1} iterations.")
            break
        print(x,iteration)
    return x
# Run the algorithm
result = KacZmarz(A, b, x, tolerance, max_iterations)
print("Approximate solution:", result)

[0.05648897 0.07156765 0.18597698] 0
[0.03571161 0.07162975 0.18483788] 1
[0.01617231 0.07168811 0.18376945] 2
[-0.00220272  0.07174297  0.18276751] 3
[-0.01948284  0.07179454  0.18182808] 4
[-0.03573333  0.071843    0.18094744] 5
[-0.05101552  0.07188855  0.18012208] 6
[-0.06538714  0.07193135  0.17934871] 7
[-0.07890245  0.07197158  0.17862423] 8
[-0.09161247  0.07200939  0.17794574] 9
[-0.10356519  0.07204491  0.17731048] 10
[-0.11480576  0.07207829  0.17671588] 11
[-0.1253766   0.07210965  0.17615952] 12
[-0.13531764  0.07213912  0.17563912] 13
[-0.14466639  0.0721668   0.17515254] 14
[-0.15345817  0.07219281  0.17469775] 15
[-0.16172616  0.07221724  0.17427288] 16
[-0.16950158  0.07224019  0.17387613] 17
[-0.17681377  0.07226174  0.17350582] 18
[-0.18369036  0.07228198  0.17316039] 19
[-0.19015729  0.07230099  0.17283834] 20
[-0.19623899  0.07231884  0.1725383 ] 21
[-0.2019584   0.07233559  0.17225893] 22
[-0.20733712  0.07235133  0.17199902] 23
[-0.21239545  0.07236609  0.1717574

Converged after 21 iterations.
Approximate solution: [0.49999911 0.99999994 0.50000032]


how i programme it 

quite disgusting but fonctionnelle 

In [66]:
def KacZmarz(matrice_A, matrice_b, inconnue):
    for iteration in range(max_iterations):
        x_old = inconnue.copy()  # Copie de l'ancienne solution
        for indise, equation in enumerate(matrice_A):
            transposer_a = 0
            norme = 0
            for j, element in enumerate(equation):
                transposer_a += element * inconnue[j]  # Produit scalaire de la ligne et de x
                norme += element * element  # Norme de la ligne

            # Mise à jour selon l'algorithme de Kaczmarz
            atixi = (matrice_b[indise] - transposer_a) / norme
            for j, element in enumerate(equation):
                inconnue[j] = inconnue[j] + atixi * element

        # Critère de convergence (tolérance)
        if np.linalg.norm(np.array(inconnue) - np.array(x_old)) < tolerance:
            print(f"Convergence atteinte après {iteration + 1} loop.")
            break

    return inconnue
# Exécution de l'algorithme
resulte = KacZmarz(A, b, x)

print("Solution approchée:", resulte)

Solution approchée: [-0.3177361   0.0680776   0.63551848]


Convergence atteinte après 21 loop.
Solution approchée: [0.49999911 0.99999994 0.50000032]


## Algorithme de Gauss-Seidel distribué

In [22]:
def has_converged(x_new, x_old, tol):
    return np.linalg.norm(x_new - x_old) < tol

# Algorithme de Gauss-Seidel distribué
def distributed_gauss_seidel(A, b, x, tolerance, max_iterations, alpha):
    n = len(b)
    x_old = np.zeros_like(x)

    for iteration in range(max_iterations):
        x_old[:] = x  # Sauvegarde de l'état précédent

        for i in range(n):  # Chaque agent résout son équation
            sum_except_i = np.dot(A[i, :], x) - A[i, i] * x[i]
            x[i] = (b[i] - sum_except_i) / A[i, i]

        # Appliquer le facteur de relaxation
        x = alpha * x + (1 - alpha) * x_old

        # Vérifier la convergence
        if has_converged(x, x_old, tolerance):
            print(f"Converged after {iteration + 1} iterations.")
            break

    return x

# Exécution de l'algorithme
x_solution = distributed_gauss_seidel(A, b, x, tolerance, max_iterations, alpha)
print("Solution trouvée : ", x_solution)

# Vérification en multipliant la solution avec A
print("Vérification : A * x =", np.dot(A, x_solution))


Solution trouvée :  [nan nan nan]
Vérification : A * x = [nan nan nan]


In [26]:
n_agents = 3              # 3 agents

# Initialisation des solutions locales aléatoires pour chaque agent
x_local = [np.random.rand(3) for _ in range(n_agents)]
x_global = np.zeros(3)

# Facteur de relaxation et nombre d'itérations
alpha = 1.0
num_iterations = 100

# Voisinage des agents (ici tout le monde est voisin)
neighbors = {0: [1, 2], 1: [0, 2], 2: [0, 1]}

# Algorithme de Kaczmarz décentralisé
for k in range(num_iterations):
    x_new_local = []
    
    # Mise à jour de chaque agent
    for i in range(n_agents):
        a_i = A[i, :]  # Vecteur d'équation pour l'agent i
        b_i = b[i]     # Valeur de b pour l'agent i
        
        # Mise à jour selon Kaczmarz
        x_local[i] = x_local[i] + alpha * (b_i - np.dot(a_i, x_local[i])) / np.dot(a_i, a_i) * a_i
        
        # Communication : chaque agent reçoit les estimations de ses voisins
        neighbors_estimates = [x_local[j] for j in neighbors[i]]
        
        # Moyenne avec les voisins
        x_local[i] = (x_local[i] + sum(neighbors_estimates)) / (len(neighbors[i]) + 1)
    
    # Affichage de l'estimation après chaque itération
    print(f"Iteration {k+1}, estimations locales : {x_local}")

# Les solutions finales pour chaque agent convergeront vers la solution globale


Iteration 1, estimations locales : [array([0.65802883, 0.2188211 , 0.48951499]), array([0.7567648 , 0.36125123, 0.44057281]), array([0.7217885 , 0.3306433 , 0.51420378])]
Iteration 2, estimations locales : [array([0.72298983, 0.30627082, 0.48682842]), array([0.80478704, 0.45095401, 0.50418145]), array([0.76212654, 0.37489413, 0.53855214])]
Iteration 3, estimations locales : [array([0.75238768, 0.37464462, 0.50439727]), array([0.82529149, 0.48714937, 0.53310731]), array([0.78742987, 0.41972401, 0.54783614])]
Iteration 4, estimations locales : [array([0.76341794, 0.42093473, 0.51597104]), array([0.83648276, 0.51666324, 0.54711694]), array([0.80030224, 0.45696604, 0.55055086])]
Iteration 5, estimations locales : [array([0.76790583, 0.45681422, 0.52179871]), array([0.84042414, 0.54158205, 0.55277568]), array([0.80563738, 0.48788075, 0.54998834])]
Iteration 6, estimations locales : [array([0.7683361 , 0.48634575, 0.52336107]), array([0.8396004 , 0.5632715 , 0.55364209]), array([0.80623726, 

24 回のループで収束しました。
近似解: [0.49999943 0.99999987 0.50000023]
